#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l pmem=2000mb
#PBS -l walltime=6:00:00
#PBS -d /storage/home/ssobie/code/repos/ClimDown/R/
#PBS -N cnr-count

gcm="CNRM-CM5"
varname="sic"

cd /storage/home/ssobie/code/repos/ipcc/
echo "Current working directory is `pwd`"

module load R/3.2.5
module load netcdf-bin
module load cdo-bin
module load nco-bin

nohup R CMD BATCH "--args tmpdir='/local_temp/ssobie/count/' gcm='$gcm' varname='$varname'" count.snow.ice.days.r "./${gcm}.${varname}.count.out"

